pub_cache:
  folder: ~/.pub-cache

task:
  container:
    dockerfile: .ci/Dockerfile
  upgrade_script:
    - flutter channel stable
    - flutter upgrade
    - flutter channel master
    - flutter upgrade
    - git fetch origin master
  activate_script: pub global activate flutter_plugin_tools
  allow_failures: $CHANNEL == "master"
  matrix:
    - name: analyze
      env:
        matrix:
          CHANNEL: "master"
          CHANNEL: "stable"
      test_script: 
        - flutter channel $CHANNEL
        - flutter pub get
        - flutter analyze
    - name: test
      env:
        CODECOV_TOKEN: ENCRYPTED[9ba9d1e58de2fc81556d89154383b44d9360408c6e7f40f5f7940d42b6c5bbac1cfb9c773ddcc20db6eba85622a3db38]
        matrix:
          CHANNEL: "master"
          CHANNEL: "stable"
      test_script:
        - flutter channel $CHANNEL
        - flutter test --coverage
        - if [ $CHANNEL = "stable" ]; then bash <(curl -s https://codecov.io/bash); fi


task:
  container:
    dockerfile: .ci/Dockerfile
    kvm: true
    cpu: 8
    memory: 16G
  env:
    matrix:
      CHANNEL: "master"
      CHANNEL: "stable"
  allow_failures: $CHANNEL == "master"
  name: e2e
  upgrade_script:
    - flutter channel stable
    - flutter upgrade
    - flutter channel master
    - flutter upgrade
    - git fetch origin master
  activate_script: pub global activate flutter_plugin_tools
  accel_check_script:
    - sudo chown cirrus:cirrus /dev/kvm
    - $ANDROID_HOME/emulator/emulator -accel-check
  create_device_script:
    echo no | avdmanager create avd --force
      -n test
      -k "system-images;android-29;default;x86"
  start_emulator_background_script:
    $ANDROID_HOME/emulator/emulator
      -avd test
      -no-audio
      -no-window
  wait_for_emulator_script:
    - adb wait-for-device
  test_script:
    - flutter channel $CHANNEL
    - cd example
    - flutter build apk
    - cd android
    - ./gradlew app:connectedAndroidTest -Ptarget=`pwd`/../../test/location_e2e.dart
