name: Deploy web demo

on:
  push:
    branches: [master]
    paths:
      - "packages/location/example/**"
      - "packages/location/lib/**"
      - "packages/location_platform_interface/**"
      - "packages/location_web/**"
      - ".github/workflows/deploy-web-demo.yaml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Set up Melos
        run: dart pub global activate melos

      - name: melos bootstrap
        run: melos bootstrap

      - name: Build web demo
        working-directory: packages/location/example
        run: flutter build web --base-href /flutterlocation/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/location/example/build/web

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
