name: location desktop

on:
  workflow_dispatch:
  pull_request:
    branches: [master, develop]

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Linux build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev

      - name: Set up Melos
        run: dart pub global activate melos

      - name: melos bootstrap
        run: melos bootstrap

      - name: Build example app
        working-directory: packages/location/example
        run: flutter build linux --debug

  build-windows:
    name: Windows
    runs-on: windows-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Set up Melos
        run: dart pub global activate melos

      - name: melos bootstrap
        run: melos bootstrap

      - name: Build example app
        working-directory: packages/location/example
        run: flutter build windows --debug
